services:
  - type: web
    name: blog-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://beokd64:85211@cluster0.cbtbxx0.mongodb.net/blog?retryWrites=true&w=majority&appName=Cluster0

